# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jin Zhang
tagline:          'Jin's blog'
description:      'Jin's data blog'
url:              http://jin-data.com
baseurl:          /

author:
  name:           'Jin Zhang'
  url:            /

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jinzh2011/jinzh2011.github.io
